routes/web.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\DepartmentController;
use App\Http\Controllers\Admin\FaqController;
use App\Http\Controllers\Admin\FeeController;
use App\Http\Controllers\Admin\NoticeController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\TokenController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Website\CesController;
use App\Http\Controllers\Website\CesResultController;
use App\Http\Controllers\Website\ContactMessageController;
use App\Http\Controllers\Website\HomeController;
use App\Http\Controllers\Website\PostGradApplicationController;
use App\Http\Controllers\Website\PostGradController;
use App\Http\Controllers\Website\StudentRegistrationController;
use App\Http\Controllers\Website\UnderGradController;
use App\Http\Controllers\Website\UtmeResultCheckerController;
use Illuminate\Support\Facades\Route;
use Spatie\MediaLibrary\MediaCollections\Models\Media as MediaAlias;

// cache clear
Route::get('reboot', function () {
    Artisan::call('cache:clear');
    Artisan::call('view:clear');
    Artisan::call('route:clear');
    Artisan::call('config:clear');
    Artisan::call('config:cache');
    dd('Done');
});
Route::get('storageLink', function () {
    Artisan::call('storage:link');
    dd('Done');
});

Route::prefix('dashboard')->middleware(['auth', 'verified'])->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('user', UserController::class);
    Route::resource('faq', FaqController::class)->except('index', 'show');
    Route::resource('contact-message', ContactMessageController::class)->except(['show', 'create', 'edit', 'update']);
    Route::resource('notice', NoticeController::class)->except('show');
    Route::resource('fee', FeeController::class)->except('create', 'store');
    Route::resource('token', TokenController::class);
    Route::resource('department', DepartmentController::class);

    Route::get('inactive-user/{user}', [UserController::class, 'inactiveUser'])->name('user.inactive');
    Route::get('active-user/{user}', [UserController::class, 'activeUser'])->name('user.active');
    Route::get('post-grad', [\App\Http\Controllers\Admin\PostGradController::class, 'index'])->name('post.grad.fee.list');
    Route::delete('deletePostgrads/{id}', [\App\Http\Controllers\Admin\PostGradController::class, 'destroy'])->name('deletePostgrads');
    Route::get('post-grad-application', [\App\Http\Controllers\Admin\PostGradApplicationController::class, 'index'])->name('post.grad.application.fee.list');
    Route::delete('deletePostGradApplication/{id}', [\App\Http\Controllers\Admin\PostGradApplicationController::class, 'destroy'])->name('deletePostGradApplication');
    Route::get('under-grad', [\App\Http\Controllers\Admin\UnderGradController::class, 'index'])->name('under.grad.fee.list');
    Route::delete('deleteUnderGradApplication/{id}', [\App\Http\Controllers\Admin\UnderGradController::class, 'destroy'])->name('deleteUnderGradApplication');
    Route::get('ces', [\App\Http\Controllers\Admin\CesController::class, 'index'])->name('ces.fee.list');
    Route::delete('deleteCes/{id}', [\App\Http\Controllers\Admin\CesController::class, 'destroy'])->name('deleteCes');
    Route::get('utme-result', [\App\Http\Controllers\Admin\UtmeResultCheckerController::class, 'index'])->name('utme.result.fee.list');
    Route::delete('deleteUtme/{id}', [\App\Http\Controllers\Admin\UtmeResultCheckerController::class, 'destroy'])->name('deleteUtme');
    Route::get('ces-result', [\App\Http\Controllers\Admin\CesResultController::class, 'index'])->name('ces.result.fee.list');
    Route::delete('deleteCesResult/{id}', [\App\Http\Controllers\Admin\CesResultController::class, 'destroy'])->name('deleteCesResult');
    Route::get('token-receipt/{for}/{id}', [\App\Http\Controllers\Admin\MakePdfController::class, 'makePdf'])->name('token_receipt');

    Route::get('edit-profile', [UserController::class, 'editProfile'])->name('edit.profile');
    Route::get('change_password', [UserController::class, 'change_password'])->name('change_password');
    Route::get('settings/company_settings', [SettingController::class, 'editCompanySetting'])->name('company.edit');
    Route::post('settings/company_setting', [SettingController::class, 'updateCompanySetting'])->name('company.update');

    Route::delete('remove-media/{media}', function (MediaAlias $media) {
        $media->delete();
        return back()->with('success', 'Media successfully deleted.');
    })->name('remove-media');

    // Role Permission
    Route::resource('developer/permission', PermissionController::class)->only('index', 'store');
    Route::get('role/assign', [RoleController::class, 'roleAssign'])->name('role.assign');
    Route::post('role/assign', [RoleController::class, 'storeAssign'])->name('store.assign');
    Route::resource('role', RoleController::class);

    Route::get('export-csv-file/{slug}', [\App\Http\Controllers\Admin\PostGradController::class, 'exportCSV']);
    Route::get('export-csv-file-PostGradApplication/{slug}', [\App\Http\Controllers\Admin\PostGradApplicationController::class, 'exportCSVPostGradApplication']);
    Route::get('export-csv-file-underGrad/{slug}', [\App\Http\Controllers\Admin\UnderGradController::class, 'exportCSVUnderGrad']);
    Route::get('export-csv-file-CES/{slug}', [\App\Http\Controllers\Admin\CesController::class, 'exportCSVCES']);
    Route::get('export-csv-file-CES-Result/{slug}', [\App\Http\Controllers\Admin\CesResultController::class, 'exportCSVCESResult']);
    Route::get('export-csv-file-utmeResult/{slug}', [\App\Http\Controllers\Admin\UtmeResultCheckerController::class, 'exportUTMEResultResult']);
});

Route::middleware('web')->group(function () {
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::resource('registration', StudentRegistrationController::class);
    Route::middleware(['auth'])->group(function () {
        Route::resource('postGrad', PostGradController::class)->only('create', 'store', 'show');
        Route::resource('postGradApplication', PostGradApplicationController::class)->only('create', 'store', 'show');
        Route::resource('underGrad', UnderGradController::class)->only('create', 'store', 'show');
        Route::resource('ces', CesController::class)->only('create', 'store', 'show');
        Route::resource('utmeResult', UtmeResultCheckerController::class)->only('create', 'store', 'show');
        Route::resource('cesResult', CesResultController::class)->only('create', 'store', 'show');
        Route::get('complete_order', [HomeController::class, 'completeOrder'])->name('complete.order');
    });
});

app/Http/Controllers/Admin/DashboardController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\PostGrad;
use App\Models\PostGradApplication;
use App\Models\UnderGrad;
use App\Models\Ces;
use App\Models\CesResult;
use App\Models\UtmeResultChecker;
use App\Models\User;
use App\Models\Department;

class DashboardController extends Controller
{
    public function index()
    {
        $users = User::count();
        $departments = Department::count();
        $totalUnPaidFeePostGrad = PostGrad::query()
            ->when(auth()->user()->hasRole('User'), fn ($q) => $q->where('user_id', auth()->id()))
            ->where('payment_status', 0)
            ->count();
        $totalPaidFeePostGrad = PostGrad::query()
            ->when(auth()->user()->hasRole('User'), fn ($q) => $q->where('user_id', auth()->id()))
            ->where('payment_status', 1)
            ->count();
        $totalUnPaidFeePostGradApplication = PostGradApplication::query()
            ->when(auth()->user()->hasRole('User'), fn ($q) => $q->where('user_id', auth()->id()))
            ->where('payment_status', 0)
            ->count();
        $totalPaidFeePostGradApplication = PostGradApplication::query()
            ->when(auth()->user()->hasRole('User'), fn ($q) => $q->where('user_id', auth()->id()))
            ->where('payment_status', 1)
            ->count();
        $totalUnPaidFeeUnderGrad = UnderGrad::query()
            ->when(auth()->user()->hasRole('User'), fn ($q) => $q->where('user_id', auth()->id()))
            ->where('payment_status', 0)
            ->count();
        $totalPaidFeeUnderGrad = UnderGrad::query()
            ->when(auth()->user()->hasRole('User'), fn ($q) => $q->where('user_id', auth()->id()))
            ->where('payment_status', 1)
            ->count();
        $totalUnPaidFeeCes = Ces::query()
            ->when(auth()->user()->hasRole('User'), fn ($q) => $q->where('user_id', auth()->id()))
            ->where('payment_status', 0)
            ->count();
        $totalPaidFeeCes = Ces::query()
            ->when(auth()->user()->hasRole('User'), fn ($q) => $q->where('user_id', auth()->id()))
            ->where('payment_status', 1)
            ->count();
        $totalUnPaidFeeCesResult = CesResult::query()
            ->when(auth()->user()->hasRole('User'), fn ($q) => $q->where('user_id', auth()->id()))
            ->where('payment_status', 0)
            ->count();
        $totalPaidFeeCesResult = CesResult::query()
            ->when(auth()->user()->hasRole('User'), fn ($q) => $q->where('user_id', auth()->id()))
            ->where('payment_status', 1)
            ->count();
        $totalUnPaidFeeUtmeResultChecker = UtmeResultChecker::query()
            ->when(auth()->user()->hasRole('User'), fn ($q) => $q->where('user_id', auth()->id()))
            ->where('payment_status', 0)
            ->count();
        $totalPaidFeeUtmeResultChecker = UtmeResultChecker::query()
            ->when(auth()->user()->hasRole('User'), fn ($q) => $q->where('user_id', auth()->id()))
            ->where('payment_status', 1)
            ->count();

        $totalPaidFee = $totalPaidFeePostGrad + $totalPaidFeePostGradApplication + $totalPaidFeeUnderGrad + $totalPaidFeeCes + $totalPaidFeeCesResult + $totalPaidFeeUtmeResultChecker;
        $totalUnpaidFee = $totalUnPaidFeePostGrad + $totalUnPaidFeePostGradApplication + $totalUnPaidFeeUnderGrad + $totalUnPaidFeeCes + $totalUnPaidFeeCesResult + $totalUnPaidFeeUtmeResultChecker;

        return view('dashboard.dashboard', compact('users', 'departments', 'totalPaidFee', 'totalUnpaidFee'));
    }
}

resources/views/dashboard/dashboard.blade.php
@extends('layouts.dashboard')

@section('content')
  <div class="row">
    <div class="col-lg-12">
      <div class="card card-custom bg-gray-100 card-stretch gutter-b">
        <div class="card-header border-0 bg-primary py-5">
          <h3 class="card-title font-weight-bolder text-white">Dashboard</h3>
        </div>
        <div class="card-body p-0 position-relative overflow-hidden">
          <div id="kt_mixed_widget_1_chart" class="card-rounded-bottom bg-primary" style="height: 100px; min-height: 100px;">
          </div>
          <div class="card-spacer mt-n25">
            @can('transaction.access')
              <div class="row m-0">
                <div class="col bg-light-success px-6 py-8 rounded-xl mr-7 mb-7">
                  <span class="svg-icon svg-icon-3x svg-icon-success d-block my-2">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                      <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                        <rect x="0" y="0" width="24" height="24"></rect>
                        <rect fill="#000000" opacity="0.3" x="13" y="4" width="3" height="16" rx="1.5"></rect>
                        <rect fill="#000000" x="8" y="9" width="3" height="11" rx="1.5"></rect>
                        <rect fill="#000000" x="18" y="11" width="3" height="9" rx="1.5"></rect>
                        <rect fill="#000000" x="3" y="13" width="3" height="7" rx="1.5"></rect>
                      </g>
                    </svg>
                  </span>
                  <p class="text-success font-weight-bold font-size-h6">Paid Transaction : {{ $totalPaidFee }}</p>
                </div>
                <div class="col bg-light-warning px-6 py-8 rounded-xl mb-7">
                  <span class="svg-icon svg-icon-3x svg-icon-warning d-block my-2">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                      <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                        <rect x="0" y="0" width="24" height="24"></rect>
                        <rect fill="#000000" opacity="0.3" x="13" y="4" width="3" height="16" rx="1.5"></rect>
                        <rect fill="#000000" x="8" y="9" width="3" height="11" rx="1.5"></rect>
                        <rect fill="#000000" x="18" y="11" width="3" height="9" rx="1.5"></rect>
                        <rect fill="#000000" x="3" y="13" width="3" height="7" rx="1.5"></rect>
                      </g>
                    </svg>
                  </span>
                  <p class="text-warning font-weight-bold font-size-h6 mt-2">Unpaid Transaction : {{ $totalUnpaidFee }}</p>
                </div>
              </div>
            @endcan
            <div class="row m-0">
              @can('department.access')
                <div class="col bg-light-danger px-6 py-8 rounded-xl mr-7 mb-7">
                  <span class="svg-icon svg-icon-3x svg-icon-danger d-block my-2">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                      <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                        <polygon points="0 0 24 0 24 24 0 24"></polygon>
                        <path
                          d="M12.9336061,16.072447 L19.36,10.9564761 L19.5181585,10.8312381 C20.1676248,10.3169571 20.2772143,9.3735535 19.7629333,8.72408713 C19.6917232,8.63415859 19.6104327,8.55269514 19.5206557,8.48129411 L12.9336854,3.24257445 C12.3871201,2.80788259 11.6128799,2.80788259 11.0663146,3.24257445 L4.47482784,8.48488609 C3.82645598,9.00054628 3.71887192,9.94418071 4.23453211,10.5925526 C4.30500305,10.6811601 4.38527899,10.7615046 4.47382636,10.8320511 L4.63,10.9564761 L11.0659024,16.0730648 C11.6126744,16.5077525 12.3871218,16.5074963 12.9336061,16.072447 Z"
                          fill="#000000" fill-rule="nonzero"></path>
                        <path
                          d="M11.0563554,18.6706981 L5.33593024,14.122919 C4.94553994,13.8125559 4.37746707,13.8774308 4.06710397,14.2678211 C4.06471678,14.2708238 4.06234874,14.2738418 4.06,14.2768747 L4.06,14.2768747 C3.75257288,14.6738539 3.82516916,15.244888 4.22214834,15.5523151 C4.22358765,15.5534297 4.2250303,15.55454 4.22647627,15.555646 L11.0872776,20.8031356 C11.6250734,21.2144692 12.371757,21.2145375 12.909628,20.8033023 L19.7677785,15.559828 C20.1693192,15.2528257 20.2459576,14.6784381 19.9389553,14.2768974 C19.9376429,14.2751809 19.9363245,14.2734691 19.935,14.2717619 L19.935,14.2717619 C19.6266937,13.8743807 19.0546209,13.8021712 18.6572397,14.1104775 C18.654352,14.112718 18.6514778,14.1149757 18.6486172,14.1172508 L12.9235044,18.6705218 C12.377022,19.1051477 11.6029199,19.1052208 11.0563554,18.6706981 Z"
                          fill="#000000" opacity="0.3"></path>
                      </g>
                    </svg>
                  </span>
                  <a href="{{ route('department.index') }}" class="text-danger font-weight-bold font-size-h6 mt-2">Departments : {{ $departments }}</a>
                </div>
              @endcan
              @can('user.access')
                <div class="col bg-light-primary px-6 py-8 rounded-xl mb-7">
                  <span class="svg-icon svg-icon-3x svg-icon-primary d-block my-2">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                      <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                        <polygon points="0 0 24 0 24 24 0 24"></polygon>
                        <path
                          d="M18,8 L16,8 C15.4477153,8 15,7.55228475 15,7 C15,6.44771525 15.4477153,6 16,6 L18,6 L18,4 C18,3.44771525 18.4477153,3 19,3 C19.5522847,3 20,3.44771525 20,4 L20,6 L22,6 C22.5522847,6 23,6.44771525 23,7 C23,7.55228475 22.5522847,8 22,8 L20,8 L20,10 C20,10.5522847 19.5522847,11 19,11 C18.4477153,11 18,10.5522847 18,10 L18,8 Z M9,11 C6.790861,11 5,9.209139 5,7 C5,4.790861 6.790861,3 9,3 C11.209139,3 13,4.790861 13,7 C13,9.209139 11.209139,11 9,11 Z"
                          fill="#000000" fill-rule="nonzero" opacity="0.3"></path>
                        <path
                          d="M0.00065168429,20.1992055 C0.388258525,15.4265159 4.26191235,13 8.98334134,13 C13.7712164,13 17.7048837,15.2931929 17.9979143,20.2 C18.0095879,20.3954741 17.9979143,21 17.2466999,21 C13.541124,21 8.03472472,21 0.727502227,21 C0.476712155,21 -0.0204617505,20.45918 0.00065168429,20.1992055 Z"
                          fill="#000000" fill-rule="nonzero"></path>
                      </g>
                    </svg>
                  </span>
                  <a href="{{ route('user.index') }}" class="text-primary font-weight-bold font-size-h6 mt-2">Users : {{ $users }}</a>
                </div>
              @endcan
            </div>
          </div>
          <div class="resize-triggers">
            <div class="expand-trigger">
              <div style="width: 414px; height: 462px;"></div>
            </div>
            <div class="contract-trigger"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection